### ISSUE TITLE
Missing types "index.d.ts"

### ISSUE THREAD

**Issue by gurvancampion** [utkarsh867/typegraphql-authchecker#1]
First thanks for this plugin!
Just noticed after installing the package via pnpm, the types are missing in the build directory `lib`, I only see index.js

**Comment by utkarsh867** [comment]
Thanks a lot @gurvan-guss 

Will look into it! Let me know if you wanna go at it to fix the issue.

**Comment by utkarsh867** [comment]
It was a little bug.

Fixed in 0.0.3 (f3627bc125f97e4058a5bb6d041a68a9a79db6e7)
