### ISSUE TITLE
Check if same user

### ISSUE THREAD

**Issue by jaymarkjairi** [utkarsh867/typegraphql-authchecker#2]
1st user is login then the 2nd user is login 
is there any features that checks the latest login user?, the 1st user will not authorize anymore.

this is base on graphql shield 
const isReadingOwnAccount = rule()((parent, { id }, { user }) => {
  return user && user.sub === id;
});

thank you...

**Comment by orefalo** [comment]
Sorry, but I don't understand the code above. It seems to be disconnected from the use case.
Can you provide mode details?

What is the capability that you are pointing at in shield?

**Comment by utkarsh867** [comment]
@jaymarkjairi I'm going to close this issue since it is unrelated to this package.
