### ISSUE TITLE
Add Examples

### ISSUE THREAD

**Issue by tsanyqudsi** [utkarsh867/typegraphql-authchecker#3]
Could you add few examples for this plugin ?

**Comment by utkarsh867** [comment]
That's been on my mind. Will work on adding a few examples this holidays :)

For some examples to begin with, you can take a look at the docs and the tests as well!

**Comment by tsanyqudsi** [comment]
@utkarsh867 will do. To add, i found this module from this [blog](https://javachipd.medium.com/authorization-in-typegraphql-with-permission-layer-like-graphql-shield-87cd8b0b0e47). I believe it's yours ? 

"typegraphql-authchecker. I love using TypeGraphQL and Prisma." the typegraphql-authchecker link is not linking to this module's github / npm. You might want to change it.

**Comment by utkarsh867** [comment]
> @utkarsh867 will do. To add, i found this module from this [blog](https://javachipd.medium.com/authorization-in-typegraphql-with-permission-layer-like-graphql-shield-87cd8b0b0e47). I believe it's yours ?
> 
> "typegraphql-authchecker. I love using TypeGraphQL and Prisma." the typegraphql-authchecker link is not linking to this module's github / npm. You might want to change it.

Thanks for the heads up!
