### ISSUE TITLE
type-graphql v2.0 support?

### ISSUE THREAD

**Issue by yourbuddyconner** [utkarsh867/typegraphql-authchecker#9]
Hey @utkarsh867! 

Wondering if you have any intuition around what might be needed in this library to support the beta version ([thread](https://github.com/MichalLytek/type-graphql/issues/1418)) of `type-graphql@2.0.0-beta.2` which has support for `graphql@^16`

Would be happy to contribute the change if you point me in the right direction!

**Comment by yourbuddyconner** [comment]
Log of what I have done: 

First, I forked the repo, updated to `"graphql": "^16.7.1",` and `"type-graphql": "^2.0.0-beta.2"`
This builds alright, however I run into the following runtime error: 
```
stacktrace": [
          "TypeError: Cannot read properties of undefined (reading 'root')",
          "    at new authChecker (/Users/.../node_modules/typegraphql-authchecker/lib/index.js:152:19)",
...
```

Have been trying to debug, but the recursive nature of this library throws me through a couple loops...

Clearly, the `ResolverData` argument isnt being set properly in the `type-graphql` stack, but the question is... why?

**Comment by yourbuddyconner** [comment]
Ok, 6 hours later, this ended up being a one-line change... Will document _why_ in the PR.

**Comment by utkarsh867** [comment]
Thanks a lot @yourbuddyconner  for the PR!

I will quickly have a look.
